From production@webtv.net Mon Oct 20 14:01:59 1997
From: tomita@webtv.co.jp (Y. Tomita)
Date: Tue, 16 Sep 1997 08:27:55 +0900 (JST)
To: NYLive@webtv.net
Subject: Video Greetings!
Content-Type: text/html

Greetings from WebTV Japan!
<P>

<table><tr><td>
<a href="wtv-content:/demos/VideoEmail/WebTVJapan.html"><img src="wtv-content:/demos/VideoEmail/FileMovie.gif"
	align=absmiddle valign=4 hspace=4 vspace=4>
VideoFlash attachment
<spacer width=4></a>
</table>
